# Generated by Django 4.1.7 on 2023-11-20 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_book_average_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(default=11, max_length=13),
            preserve_default=False,
        ),
    ]
